name: Code Integration Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: /Web App/thesis-webapp/package-lock.json
    - run: npm ci
      working-directory: /Web App/thesis-webapp
    - run: npm run build --if-present
      working-directory: /Web App/thesis-webapp
    - run: npm test
      working-directory: /Web App/thesis-webapp
